In [1]:
import numpy as np

In [2]:
array = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
array
print(array.ndim)
print(array.shape)

2
(3, 3)


In [ ]:
# Buscar elemento na linha 1 e coluna 2
elemento = array[1,2]
elemento

np.int64(30)

In [8]:
linha_0 = array[0]
linha_0

array([10, 20, 30])

In [11]:
# Acessando a coluna 1
coluna_1 = array[:, 1]
coluna_1

array([20, 50, 80])

In [17]:
# Fatiando para obter um subarray
# linha 0 a 1 | Coluna 1 a 2
subarray = array[0:2, 1:3]
subarray

array([[20, 30],
       [50, 60]])

In [19]:
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [20]:
elementos_maiores_que_50 = array[mascara]
elementos_maiores_que_50

array([60, 70, 80, 90])

In [21]:
# Modificando elemento na linha 1, coluna 1
array[1, 1] = 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])