Copy
- Uma nova cópia do array é criada em memória.
Isso significa que as 2 matrizes (original e a cópia) são independentes uma da outra.

View
- Não é criada uma nova cópia na memória.
A view não é criada em uma nova cópiana memória. A view compartilha os mesmos dados que o array original.

In [3]:
import numpy as np

In [4]:
array_original = np.array([[1, 2, 3], 
                          [4, 5, 6], 
                          [7, 8, 9]])
array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# 1-Cópia Rasa (View)
array_view = array_original[1:, 1:]
array_view

array([[5, 6],
       [8, 9]])

In [8]:
array_view[0, 0] = 99
array_view

array([[99,  6],
       [ 8,  9]])

In [9]:
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [10]:
# 2-Cópia Profunda (Copy)
array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [13]:
array_copia[0, 0] = 100
print("Cópia: ",array_copia)
print("Original: ",array_original)

Cópia:  [[100   2   3]
 [  4  99   6]
 [  7   8   9]]
Original:  [[ 1  2  3]
 [ 4 99  6]
 [ 7  8  9]]
